### ISSUE TITLE
Remove f-strings for Backwards Compatibility 

### ISSUE THREAD

**Issue by Bubba-che** [veggiedefender/http-server#8]
It is generally considered to be more Pythonic this way.

**Comment by veggiedefender** [comment]
I feel like f-strings are super handy, but I see what you mean, and I'll swap them out for `.format()` when I have the time. My impression of them was that they're pythonic if you don't do anything complex or side-effect-y inside them. Do you have any sources or links to discussion on this?

P.S. how'd you find this repo haha

**Comment by Bubba-che** [comment]
Oh man I look like a real punk. I had thought I read in PEP 8 that code should always be backwards compatible if possible. Turns out I was misremembering it say "feel free to ignore these guidelines if your code must be backwards compatible".

Hahah I was just perusing small Python projects to get more practice reading other people's code without having to look at a hundred files.

**Comment by veggiedefender** [comment]
lol don't worry, happens to everyone
